$(document).ready(function() { 
  	try {
	(function(){var a={},b=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),16);return 0};(function(){$('link[type="text/css"]').each(function(){var b=($(this).attr("href")||"").match(/\/?css\/([\w\-]+\.css)\?(\d+)/);b&&b[1]&&b[2]&&(a[b[1]]=b[2])})})();(function(){$("body").append('<div class="version" style="display:none; width:1px; height:1px;"></div>');
	for(var c=$(".version"),d=0;d<Muse.assets.required.length;){var f=Muse.assets.required[d],g=f.match(/([\w\-\.]+)\.(\w+)$/),k=g&&g[1]?g[1]:null,g=g&&g[2]?g[2]:null;switch(g.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");c.addClass(k);var g=b(c.css("color")),h=b(c.css("background-color"));g!=0||h!=0?(Muse.assets.required.splice(d,1),"undefined"!=typeof a[f]&&(g!=a[f]>>>24||h!=(a[f]&16777215))&&Muse.assets.outOfDate.push(f)):d++;c.removeClass(k);break;case "js":k.match(/^jquery-[\d\.]+/gi)&&
	typeof $!="undefined"?Muse.assets.required.splice(d,1):d++;break;default:throw Error("Unsupported file type: "+g);}}c.remove();if(Muse.assets.outOfDate.length||Muse.assets.required.length)c="Some files on the server may be missing or incorrect. Clear browser cache and try again. If the problem persists please contact website author.",(d=location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi))&&Muse.assets.outOfDate.length&&(c+="\nOut of date: "+Muse.assets.outOfDate.join(",")),d&&Muse.assets.required.length&&(c+="\nMissing: "+Muse.assets.required.join(",")),alert(c)})()})();
	/* body */
	Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
	Muse.Utils.prepHyperlinks(true);/* body */
	$('#u8402').registerBackgroundPositionScrollEffect([{"in":[-Infinity,1000.8],"speed":[0,0.4]},{"in":[1000.8,Infinity],"speed":[0,0.5]}]);/* scroll effect */
	Muse.Utils.initWidget('.MenuBar', function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
	Muse.Utils.initWidget('#widgetu15608', function(elem) { new WebPro.Widget.Form(elem, {validationEvent:'submit',errorStateSensitivity:'high',fieldWrapperClass:'fld-grp',formSubmittedClass:'frm-sub-st',formErrorClass:'frm-subm-err-st',formDeliveredClass:'frm-subm-ok-st',notEmptyClass:'non-empty-st',focusClass:'focus-st',invalidClass:'fld-err-st',requiredClass:'fld-err-st',ajaxSubmit:true}); });/* #widgetu15608 */
	Muse.Utils.initWidget('#pamphletu15598', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'loose',event:'mouseover',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:false,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu15598 */
	$('#u8266').registerBackgroundPositionScrollEffect([{"in":[-Infinity,-105.2],"speed":[0,0]},{"in":[-105.2,Infinity],"speed":[0,0]}]);/* scroll effect */
	Muse.Utils.resizeHeight()/* resize height */
	$('#u8277').registerBackgroundPositionScrollEffect([{"in":[-Infinity,-105.2],"speed":[0,0.5]},{"in":[-105.2,Infinity],"speed":[0,0.5]}]);/* scroll effect */
	$('#u8300').registerBackgroundPositionScrollEffect([{"in":[-Infinity,895.8],"speed":[0,0]},{"in":[895.8,Infinity],"speed":[0,0]}]);/* scroll effect */
	$('#u8318').registerBackgroundPositionScrollEffect([{"in":[-Infinity,1005],"speed":[0.4,1]},{"in":[1005,Infinity],"speed":[0.4,1]}]);/* scroll effect */
	Muse.Utils.initWidget('#pamphletu8320', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'lightbox',event:'click',deactivationEvent:'none',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:false,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu8320 */
	Muse.Utils.initWidget('#slideshowu8861', function(elem) { $(elem).data('widget', new WebPro.Widget.ContentSlideShow(elem, {autoPlay:false,displayInterval:3000,slideLinkStopsSlideShow:false,transitionStyle:'fading',lightboxEnabled_runtime:true,shuffle:false,transitionDuration:500,enableSwipe:true,elastic:'off',resumeAutoplay:false,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false})); });/* #slideshowu8861 */
	Muse.Utils.initWidget('#pamphletu8793', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'lightbox',event:'click',deactivationEvent:'none',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu8793 */
	Muse.Utils.initWidget('#pamphletu14699', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'lightbox',event:'click',deactivationEvent:'none',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu14699 */
	$('#u8335').registerBackgroundPositionScrollEffect([{"in":[-Infinity,3337.8],"speed":[0,0]},{"in":[3337.8,Infinity],"speed":[0,0]}]);/* scroll effect */
	Muse.Utils.initWidget('#widgetu12713', function(elem) { new WebPro.Widget.Form(elem, {validationEvent:'submit',errorStateSensitivity:'high',fieldWrapperClass:'fld-grp',formSubmittedClass:'frm-sub-st',formErrorClass:'frm-subm-err-st',formDeliveredClass:'frm-subm-ok-st',notEmptyClass:'non-empty-st',focusClass:'focus-st',invalidClass:'fld-err-st',requiredClass:'fld-err-st',ajaxSubmit:true}); });/* #widgetu12713 */
	$('#u15204').registerPositionScrollEffect([{"in":[-Infinity,5712.44],"speed":[0,2]},{"in":[5712.44,Infinity],"speed":[0,1]}]);/* scroll effect */
	$('#u15209').registerPositionScrollEffect([{"in":[-Infinity,5704.04],"speed":[0,1.5]},{"in":[5704.04,Infinity],"speed":[0,1]}]);/* scroll effect */
	$('#u15214').registerPositionScrollEffect([{"in":[-Infinity,5704.04],"speed":[0,2]},{"in":[5704.04,Infinity],"speed":[0,1]}]);/* scroll effect */
	$('#u15219').registerPositionScrollEffect([{"in":[-Infinity,5704.04],"speed":[0,1.5]},{"in":[5704.04,Infinity],"speed":[0,1]}]);/* scroll effect */
	Muse.Utils.initWidget('#widgetu15689', function(elem) { new WebPro.Widget.Form(elem, {validationEvent:'submit',errorStateSensitivity:'high',fieldWrapperClass:'fld-grp',formSubmittedClass:'frm-sub-st',formErrorClass:'frm-subm-err-st',formDeliveredClass:'frm-subm-ok-st',notEmptyClass:'non-empty-st',focusClass:'focus-st',invalidClass:'fld-err-st',requiredClass:'fld-err-st',ajaxSubmit:true}); });/* #widgetu15689 */
	Muse.Utils.initWidget('#pamphletu15642', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'loose',event:'mouseover',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:false,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu15642 */
	Muse.Utils.fullPage('#page');/* 100% height page */
	Muse.Utils.showWidgetsWhenReady();/* body */
	Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
	} catch(e) { if (e && 'function' == typeof e.notify) e.notify(); else Muse.Assert.fail('Error calling selector function:' + e); }
});