$(document).ready(function() { 
   	try {
	(function(){var a={},b=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),16);return 0};(function(){$('link[type="text/css"]').each(function(){var b=($(this).attr("href")||"").match(/\/?css\/([\w\-]+\.css)\?(\d+)/);b&&b[1]&&b[2]&&(a[b[1]]=b[2])})})();(function(){$("body").append('<div class="version" style="display:none; width:1px; height:1px;"></div>');
	for(var c=$(".version"),d=0;d<Muse.assets.required.length;){var f=Muse.assets.required[d],g=f.match(/([\w\-\.]+)\.(\w+)$/),k=g&&g[1]?g[1]:null,g=g&&g[2]?g[2]:null;switch(g.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");c.addClass(k);var g=b(c.css("color")),h=b(c.css("background-color"));g!=0||h!=0?(Muse.assets.required.splice(d,1),"undefined"!=typeof a[f]&&(g!=a[f]>>>24||h!=(a[f]&16777215))&&Muse.assets.outOfDate.push(f)):d++;c.removeClass(k);break;case "js":k.match(/^jquery-[\d\.]+/gi)&&
	typeof $!="undefined"?Muse.assets.required.splice(d,1):d++;break;default:throw Error("Unsupported file type: "+g);}}c.remove();if(Muse.assets.outOfDate.length||Muse.assets.required.length)c="Some files on the server may be missing or incorrect. Clear browser cache and try again. If the problem persists please contact website author.",(d=location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi))&&Muse.assets.outOfDate.length&&(c+="\nOut of date: "+Muse.assets.outOfDate.join(",")),d&&Muse.assets.required.length&&(c+="\nMissing: "+Muse.assets.required.join(","))})()})();
	/* body */
	Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
	Muse.Utils.prepHyperlinks(true);/* body */
	$('#u9492').registerBackgroundPositionScrollEffect([{"in":[-Infinity,1000.8],"speed":[0,0.4]},{"in":[1000.8,Infinity],"speed":[0,0.5]}]);/* scroll effect */
	Muse.Utils.initWidget('.MenuBar', function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
	Muse.Utils.initWidget('#widgetu15789', function(elem) { new WebPro.Widget.Form(elem, {validationEvent:'submit',errorStateSensitivity:'high',fieldWrapperClass:'fld-grp',formSubmittedClass:'frm-sub-st',formErrorClass:'frm-subm-err-st',formDeliveredClass:'frm-subm-ok-st',notEmptyClass:'non-empty-st',focusClass:'focus-st',invalidClass:'fld-err-st',requiredClass:'fld-err-st',ajaxSubmit:true}); });/* #widgetu15789 */
	Muse.Utils.initWidget('#pamphletu15776', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'loose',event:'mouseover',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:false,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu15776 */
	$('#u9369').registerBackgroundPositionScrollEffect([{"in":[-Infinity,-105.2],"speed":[0,0]},{"in":[-105.2,Infinity],"speed":[0,0]}]);/* scroll effect */
	Muse.Utils.resizeHeight()/* resize height */
	$('#u9391').registerBackgroundPositionScrollEffect([{"in":[-Infinity,205.3],"speed":[0,0.6]},{"in":[205.3,Infinity],"speed":[0,0.6]}]);/* scroll effect */
	$('#u9316').registerBackgroundPositionScrollEffect([{"in":[-Infinity,896],"speed":[0,0]},{"in":[896,Infinity],"speed":[0,0]}]);/* scroll effect */
	$('#u9427').registerBackgroundPositionScrollEffect([{"in":[-Infinity,1027],"speed":[0,0.6]},{"in":[1027,Infinity],"speed":[0,0.6]}]);/* scroll effect */
	$('#u9435').registerBackgroundPositionScrollEffect([{"in":[-Infinity,1027],"speed":[0,0.9]},{"in":[1027,Infinity],"speed":[0,0.8]}]);/* scroll effect */
	Muse.Utils.initWidget('#pamphletu14672', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'lightbox',event:'click',deactivationEvent:'none',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu14672 */
	$('#u9305').registerBackgroundPositionScrollEffect([{"in":[-Infinity,1903.85],"speed":[0,0]},{"in":[1903.85,Infinity],"speed":[0,0]}]);/* scroll effect */
	$('#u9337').registerBackgroundPositionScrollEffect([{"in":[-Infinity,2586.83],"speed":[0,0.8]},{"in":[2586.83,Infinity],"speed":[0,0.8]}]);/* scroll effect */
	Muse.Utils.initWidget('#pamphletu9713', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu9713 */
	$('#u9839').registerBackgroundPositionScrollEffect([{"in":[-Infinity,4255],"speed":[0,0]},{"in":[4255,Infinity],"speed":[0,0]}]);/* scroll effect */
	Muse.Utils.initWidget('#widgetu15973', function(elem) { new WebPro.Widget.Form(elem, {validationEvent:'submit',errorStateSensitivity:'high',fieldWrapperClass:'fld-grp',formSubmittedClass:'frm-sub-st',formErrorClass:'frm-subm-err-st',formDeliveredClass:'frm-subm-ok-st',notEmptyClass:'non-empty-st',focusClass:'focus-st',invalidClass:'fld-err-st',requiredClass:'fld-err-st',ajaxSubmit:true}); });/* #widgetu15973 */
	$('#u15224').registerPositionScrollEffect([{"in":[-Infinity,6511.64],"speed":[0,2]},{"in":[6511.64,Infinity],"speed":[0,1]}]);/* scroll effect */
	$('#u15229').registerPositionScrollEffect([{"in":[-Infinity,6503.24],"speed":[0,1.5]},{"in":[6503.24,Infinity],"speed":[0,1]}]);/* scroll effect */
	$('#u15234').registerPositionScrollEffect([{"in":[-Infinity,6503.24],"speed":[0,2]},{"in":[6503.24,Infinity],"speed":[0,1]}]);/* scroll effect */
	$('#u15239').registerPositionScrollEffect([{"in":[-Infinity,6503.24],"speed":[0,1.5]},{"in":[6503.24,Infinity],"speed":[0,1]}]);/* scroll effect */
	Muse.Utils.initWidget('#widgetu15909', function(elem) { new WebPro.Widget.Form(elem, {validationEvent:'submit',errorStateSensitivity:'high',fieldWrapperClass:'fld-grp',formSubmittedClass:'frm-sub-st',formErrorClass:'frm-subm-err-st',formDeliveredClass:'frm-subm-ok-st',notEmptyClass:'non-empty-st',focusClass:'focus-st',invalidClass:'fld-err-st',requiredClass:'fld-err-st',ajaxSubmit:true}); });/* #widgetu15909 */
	Muse.Utils.initWidget('#pamphletu15855', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'loose',event:'mouseover',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:false,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false}); });/* #pamphletu15855 */
	Muse.Utils.fullPage('#page');/* 100% height page */
	Muse.Utils.showWidgetsWhenReady();/* body */
	Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
	} catch(e) { if (e && 'function' == typeof e.notify) e.notify(); else Muse.Assert.fail('Error calling selector function:' + e); }
});
